name: FirstWorkflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          choco install chromedriver --version=latest
          choco install googlechrome
          choco install geckodriver --version=latest
          choco install firefox
          choco install msedgedriver --version=latest
          choco install microsoft-edge

      - name: Set environment variables
        run: echo "CHROMEDRIVER_PATH=$(where chromedriver)" >> $GITHUB_ENV
      

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Run tests
        run: mvn test

